workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
        working_directory: peepl_mobile
      - name: Build APK
        script: flutter build apk --release
        working_directory: peepl_mobile
    artifacts:
      - peepl_mobile/build/**/outputs/**/*.apk

  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    integrations:
      app_store_connect: Codemagic
    environment:
      flutter: stable
      groups:
        - a
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
        working_directory: peepl_mobile
      - name: Set up keychain
        script: keychain initialize
      - name: Add certificate to keychain
        script: |
          echo $CM_CERTIFICATE | base64 --decode > /tmp/distribution.p12
          keychain add-certificates --certificate /tmp/distribution.p12 --certificate-password peepl123
      - name: Set up provisioning profile
        script: |
          echo $CM_PROVISIONING_PROFILE | base64 --decode > /tmp/profile.mobileprovision
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          UUID=$(grep -a 'UUID' -A1 /tmp/profile.mobileprovision | grep -o '[-A-Za-z0-9]\{36\}')
          cp /tmp/profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/$UUID.mobileprovision
      - name: Build iOS
        script: |
          cd peepl_mobile
          flutter build ipa --release \
            --export-options-plist=/tmp/ExportOptions.plist
        env:
          EXPANDED_CODE_SIGN_IDENTITY: "Apple Distribution: James Houston (MJZ3VHZ23U)"
    artifacts:
      - peepl_mobile/build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
